#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.33440
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htwapp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="htwdata")]
	public partial class HtwDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertDozenten(Dozenten instance);
    partial void UpdateDozenten(Dozenten instance);
    partial void DeleteDozenten(Dozenten instance);
    partial void InsertFach(Fach instance);
    partial void UpdateFach(Fach instance);
    partial void DeleteFach(Fach instance);
    partial void InsertRaum(Raum instance);
    partial void UpdateRaum(Raum instance);
    partial void DeleteRaum(Raum instance);
    partial void InsertStudiengaenge(Studiengaenge instance);
    partial void UpdateStudiengaenge(Studiengaenge instance);
    partial void DeleteStudiengaenge(Studiengaenge instance);
    #endregion
		
		public HtwDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["htwdataConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HtwDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HtwDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HtwDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HtwDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dozenten> Dozenten
		{
			get
			{
				return this.GetTable<Dozenten>();
			}
		}
		
		public System.Data.Linq.Table<Fach> Fach
		{
			get
			{
				return this.GetTable<Fach>();
			}
		}
		
		public System.Data.Linq.Table<Raum> Raum
		{
			get
			{
				return this.GetTable<Raum>();
			}
		}
		
		public System.Data.Linq.Table<Studiengaenge> Studiengaenge
		{
			get
			{
				return this.GetTable<Studiengaenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dozenten")]
	public partial class Dozenten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _nachname;
		
		private string _vorname;
		
		private string _profiladd;
		
		private string _mail;
		
		private string _tele;
		
		private string _fax;
		
		private string _sprechstunde;
		
		private string _profilbildadd;
		
		private EntitySet<Fach> _Fach;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnachnameChanging(string value);
    partial void OnnachnameChanged();
    partial void OnvornameChanging(string value);
    partial void OnvornameChanged();
    partial void OnprofiladdChanging(string value);
    partial void OnprofiladdChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnteleChanging(string value);
    partial void OnteleChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnsprechstundeChanging(string value);
    partial void OnsprechstundeChanged();
    partial void OnprofilbildaddChanging(string value);
    partial void OnprofilbildaddChanged();
    #endregion
		
		public Dozenten()
		{
			this._Fach = new EntitySet<Fach>(new Action<Fach>(this.attach_Fach), new Action<Fach>(this.detach_Fach));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nachname", DbType="VarChar(500)")]
		public string nachname
		{
			get
			{
				return this._nachname;
			}
			set
			{
				if ((this._nachname != value))
				{
					this.OnnachnameChanging(value);
					this.SendPropertyChanging();
					this._nachname = value;
					this.SendPropertyChanged("nachname");
					this.OnnachnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorname", DbType="VarChar(500)")]
		public string vorname
		{
			get
			{
				return this._vorname;
			}
			set
			{
				if ((this._vorname != value))
				{
					this.OnvornameChanging(value);
					this.SendPropertyChanging();
					this._vorname = value;
					this.SendPropertyChanged("vorname");
					this.OnvornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profiladd", DbType="VarChar(500)")]
		public string profiladd
		{
			get
			{
				return this._profiladd;
			}
			set
			{
				if ((this._profiladd != value))
				{
					this.OnprofiladdChanging(value);
					this.SendPropertyChanging();
					this._profiladd = value;
					this.SendPropertyChanged("profiladd");
					this.OnprofiladdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(500)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tele", DbType="VarChar(500)")]
		public string tele
		{
			get
			{
				return this._tele;
			}
			set
			{
				if ((this._tele != value))
				{
					this.OnteleChanging(value);
					this.SendPropertyChanging();
					this._tele = value;
					this.SendPropertyChanged("tele");
					this.OnteleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(500)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sprechstunde", DbType="VarChar(500)")]
		public string sprechstunde
		{
			get
			{
				return this._sprechstunde;
			}
			set
			{
				if ((this._sprechstunde != value))
				{
					this.OnsprechstundeChanging(value);
					this.SendPropertyChanging();
					this._sprechstunde = value;
					this.SendPropertyChanged("sprechstunde");
					this.OnsprechstundeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilbildadd", DbType="VarChar(500)")]
		public string profilbildadd
		{
			get
			{
				return this._profilbildadd;
			}
			set
			{
				if ((this._profilbildadd != value))
				{
					this.OnprofilbildaddChanging(value);
					this.SendPropertyChanging();
					this._profilbildadd = value;
					this.SendPropertyChanged("profilbildadd");
					this.OnprofilbildaddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dozenten_Fach", Storage="_Fach", ThisKey="Id", OtherKey="verantwortung")]
		public EntitySet<Fach> Fach
		{
			get
			{
				return this._Fach;
			}
			set
			{
				this._Fach.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fach(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Dozenten = this;
		}
		
		private void detach_Fach(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Dozenten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fach")]
	public partial class Fach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _bezeichnung;
		
		private string _code;
		
		private System.Nullable<int> _studiensemster;
		
		private string _ects;
		
		private System.Nullable<int> _verantwortung;
		
		private string _von;
		
		private string _bis;
		
		private System.Nullable<int> _raum;
		
		private System.Nullable<bool> _wahlfach;
		
		private string _tag;
		
		private string _modullink;
		
		private string _beschreibung;
		
		private System.Nullable<int> _studiengang;
		
		private EntityRef<Dozenten> _Dozenten;
		
		private EntityRef<Raum> _Raum1;
		
		private EntityRef<Studiengaenge> _Studiengaenge;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnbezeichnungChanging(string value);
    partial void OnbezeichnungChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnstudiensemsterChanging(System.Nullable<int> value);
    partial void OnstudiensemsterChanged();
    partial void OnectsChanging(string value);
    partial void OnectsChanged();
    partial void OnverantwortungChanging(System.Nullable<int> value);
    partial void OnverantwortungChanged();
    partial void OnvonChanging(string value);
    partial void OnvonChanged();
    partial void OnbisChanging(string value);
    partial void OnbisChanged();
    partial void OnraumChanging(System.Nullable<int> value);
    partial void OnraumChanged();
    partial void OnwahlfachChanging(System.Nullable<bool> value);
    partial void OnwahlfachChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void OnmodullinkChanging(string value);
    partial void OnmodullinkChanged();
    partial void OnbeschreibungChanging(string value);
    partial void OnbeschreibungChanged();
    partial void OnstudiengangChanging(System.Nullable<int> value);
    partial void OnstudiengangChanged();
    #endregion
		
		public Fach()
		{
			this._Dozenten = default(EntityRef<Dozenten>);
			this._Raum1 = default(EntityRef<Raum>);
			this._Studiengaenge = default(EntityRef<Studiengaenge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung", DbType="VarChar(500)")]
		public string bezeichnung
		{
			get
			{
				return this._bezeichnung;
			}
			set
			{
				if ((this._bezeichnung != value))
				{
					this.OnbezeichnungChanging(value);
					this.SendPropertyChanging();
					this._bezeichnung = value;
					this.SendPropertyChanged("bezeichnung");
					this.OnbezeichnungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(500)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studiensemster", DbType="Int")]
		public System.Nullable<int> studiensemster
		{
			get
			{
				return this._studiensemster;
			}
			set
			{
				if ((this._studiensemster != value))
				{
					this.OnstudiensemsterChanging(value);
					this.SendPropertyChanging();
					this._studiensemster = value;
					this.SendPropertyChanged("studiensemster");
					this.OnstudiensemsterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ects", DbType="VarChar(500)")]
		public string ects
		{
			get
			{
				return this._ects;
			}
			set
			{
				if ((this._ects != value))
				{
					this.OnectsChanging(value);
					this.SendPropertyChanging();
					this._ects = value;
					this.SendPropertyChanged("ects");
					this.OnectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verantwortung", DbType="Int")]
		public System.Nullable<int> verantwortung
		{
			get
			{
				return this._verantwortung;
			}
			set
			{
				if ((this._verantwortung != value))
				{
					if (this._Dozenten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnverantwortungChanging(value);
					this.SendPropertyChanging();
					this._verantwortung = value;
					this.SendPropertyChanged("verantwortung");
					this.OnverantwortungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_von", DbType="VarChar(50)")]
		public string von
		{
			get
			{
				return this._von;
			}
			set
			{
				if ((this._von != value))
				{
					this.OnvonChanging(value);
					this.SendPropertyChanging();
					this._von = value;
					this.SendPropertyChanged("von");
					this.OnvonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bis", DbType="VarChar(50)")]
		public string bis
		{
			get
			{
				return this._bis;
			}
			set
			{
				if ((this._bis != value))
				{
					this.OnbisChanging(value);
					this.SendPropertyChanging();
					this._bis = value;
					this.SendPropertyChanged("bis");
					this.OnbisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raum", DbType="Int")]
		public System.Nullable<int> raum
		{
			get
			{
				return this._raum;
			}
			set
			{
				if ((this._raum != value))
				{
					if (this._Raum1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnraumChanging(value);
					this.SendPropertyChanging();
					this._raum = value;
					this.SendPropertyChanged("raum");
					this.OnraumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wahlfach", DbType="Bit")]
		public System.Nullable<bool> wahlfach
		{
			get
			{
				return this._wahlfach;
			}
			set
			{
				if ((this._wahlfach != value))
				{
					this.OnwahlfachChanging(value);
					this.SendPropertyChanging();
					this._wahlfach = value;
					this.SendPropertyChanged("wahlfach");
					this.OnwahlfachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="VarChar(50)")]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modullink", DbType="VarChar(500)")]
		public string modullink
		{
			get
			{
				return this._modullink;
			}
			set
			{
				if ((this._modullink != value))
				{
					this.OnmodullinkChanging(value);
					this.SendPropertyChanging();
					this._modullink = value;
					this.SendPropertyChanged("modullink");
					this.OnmodullinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beschreibung", DbType="VarChar(5000)")]
		public string beschreibung
		{
			get
			{
				return this._beschreibung;
			}
			set
			{
				if ((this._beschreibung != value))
				{
					this.OnbeschreibungChanging(value);
					this.SendPropertyChanging();
					this._beschreibung = value;
					this.SendPropertyChanged("beschreibung");
					this.OnbeschreibungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studiengang", DbType="Int")]
		public System.Nullable<int> studiengang
		{
			get
			{
				return this._studiengang;
			}
			set
			{
				if ((this._studiengang != value))
				{
					if (this._Studiengaenge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudiengangChanging(value);
					this.SendPropertyChanging();
					this._studiengang = value;
					this.SendPropertyChanged("studiengang");
					this.OnstudiengangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dozenten_Fach", Storage="_Dozenten", ThisKey="verantwortung", OtherKey="Id", IsForeignKey=true)]
		public Dozenten Dozenten
		{
			get
			{
				return this._Dozenten.Entity;
			}
			set
			{
				Dozenten previousValue = this._Dozenten.Entity;
				if (((previousValue != value) 
							|| (this._Dozenten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dozenten.Entity = null;
						previousValue.Fach.Remove(this);
					}
					this._Dozenten.Entity = value;
					if ((value != null))
					{
						value.Fach.Add(this);
						this._verantwortung = value.Id;
					}
					else
					{
						this._verantwortung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dozenten");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Raum_Fach", Storage="_Raum1", ThisKey="raum", OtherKey="nummer", IsForeignKey=true)]
		public Raum Raum1
		{
			get
			{
				return this._Raum1.Entity;
			}
			set
			{
				Raum previousValue = this._Raum1.Entity;
				if (((previousValue != value) 
							|| (this._Raum1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Raum1.Entity = null;
						previousValue.Fach1.Remove(this);
					}
					this._Raum1.Entity = value;
					if ((value != null))
					{
						value.Fach1.Add(this);
						this._raum = value.nummer;
					}
					else
					{
						this._raum = default(Nullable<int>);
					}
					this.SendPropertyChanged("Raum1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Studiengaenge_Fach", Storage="_Studiengaenge", ThisKey="studiengang", OtherKey="Id", IsForeignKey=true)]
		public Studiengaenge Studiengaenge
		{
			get
			{
				return this._Studiengaenge.Entity;
			}
			set
			{
				Studiengaenge previousValue = this._Studiengaenge.Entity;
				if (((previousValue != value) 
							|| (this._Studiengaenge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Studiengaenge.Entity = null;
						previousValue.Fach.Remove(this);
					}
					this._Studiengaenge.Entity = value;
					if ((value != null))
					{
						value.Fach.Add(this);
						this._studiengang = value.Id;
					}
					else
					{
						this._studiengang = default(Nullable<int>);
					}
					this.SendPropertyChanged("Studiengaenge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Raum")]
	public partial class Raum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _nummer;
		
		private System.Nullable<bool> _vorlesungsraum;
		
		private System.Nullable<bool> _mitarbeiterraum;
		
		private string _dozent;
		
		private System.Nullable<int> _fach;
		
		private EntitySet<Fach> _Fach1;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnummerChanging(System.Nullable<int> value);
    partial void OnnummerChanged();
    partial void OnvorlesungsraumChanging(System.Nullable<bool> value);
    partial void OnvorlesungsraumChanged();
    partial void OnmitarbeiterraumChanging(System.Nullable<bool> value);
    partial void OnmitarbeiterraumChanged();
    partial void OndozentChanging(string value);
    partial void OndozentChanged();
    partial void OnfachChanging(System.Nullable<int> value);
    partial void OnfachChanged();
    #endregion
		
		public Raum()
		{
			this._Fach1 = new EntitySet<Fach>(new Action<Fach>(this.attach_Fach1), new Action<Fach>(this.detach_Fach1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nummer", DbType="Int")]
		public System.Nullable<int> nummer
		{
			get
			{
				return this._nummer;
			}
			set
			{
				if ((this._nummer != value))
				{
					this.OnnummerChanging(value);
					this.SendPropertyChanging();
					this._nummer = value;
					this.SendPropertyChanged("nummer");
					this.OnnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vorlesungsraum", DbType="Bit")]
		public System.Nullable<bool> vorlesungsraum
		{
			get
			{
				return this._vorlesungsraum;
			}
			set
			{
				if ((this._vorlesungsraum != value))
				{
					this.OnvorlesungsraumChanging(value);
					this.SendPropertyChanging();
					this._vorlesungsraum = value;
					this.SendPropertyChanged("vorlesungsraum");
					this.OnvorlesungsraumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mitarbeiterraum", DbType="Bit")]
		public System.Nullable<bool> mitarbeiterraum
		{
			get
			{
				return this._mitarbeiterraum;
			}
			set
			{
				if ((this._mitarbeiterraum != value))
				{
					this.OnmitarbeiterraumChanging(value);
					this.SendPropertyChanging();
					this._mitarbeiterraum = value;
					this.SendPropertyChanged("mitarbeiterraum");
					this.OnmitarbeiterraumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dozent", DbType="VarChar(500)")]
		public string dozent
		{
			get
			{
				return this._dozent;
			}
			set
			{
				if ((this._dozent != value))
				{
					this.OndozentChanging(value);
					this.SendPropertyChanging();
					this._dozent = value;
					this.SendPropertyChanged("dozent");
					this.OndozentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fach", DbType="Int")]
		public System.Nullable<int> fach
		{
			get
			{
				return this._fach;
			}
			set
			{
				if ((this._fach != value))
				{
					this.OnfachChanging(value);
					this.SendPropertyChanging();
					this._fach = value;
					this.SendPropertyChanged("fach");
					this.OnfachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Raum_Fach", Storage="_Fach1", ThisKey="nummer", OtherKey="raum")]
		public EntitySet<Fach> Fach1
		{
			get
			{
				return this._Fach1;
			}
			set
			{
				this._Fach1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fach1(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Raum1 = this;
		}
		
		private void detach_Fach1(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Raum1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Studiengaenge")]
	public partial class Studiengaenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _bezeichnung;
		
		private EntitySet<Fach> _Fach;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnbezeichnungChanging(string value);
    partial void OnbezeichnungChanged();
    #endregion
		
		public Studiengaenge()
		{
			this._Fach = new EntitySet<Fach>(new Action<Fach>(this.attach_Fach), new Action<Fach>(this.detach_Fach));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bezeichnung", DbType="VarChar(50)")]
		public string bezeichnung
		{
			get
			{
				return this._bezeichnung;
			}
			set
			{
				if ((this._bezeichnung != value))
				{
					this.OnbezeichnungChanging(value);
					this.SendPropertyChanging();
					this._bezeichnung = value;
					this.SendPropertyChanged("bezeichnung");
					this.OnbezeichnungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Studiengaenge_Fach", Storage="_Fach", ThisKey="Id", OtherKey="studiengang")]
		public EntitySet<Fach> Fach
		{
			get
			{
				return this._Fach;
			}
			set
			{
				this._Fach.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fach(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Studiengaenge = this;
		}
		
		private void detach_Fach(Fach entity)
		{
			this.SendPropertyChanging();
			entity.Studiengaenge = null;
		}
	}
}
#pragma warning restore 1591
